apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-db
  template:
    metadata:
      labels:
        app: patient-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: patientdb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: patient-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: patient-db-storage
        persistentVolumeClaim:
          claimName: patient-db-pvc
