apiVersion: v1
kind: Service
metadata:
  name: patient-db-service
spec:
  selector:
    app: patient-db
  ports:
  - protocol: TCP
    port: 5432  # Service port
    targetPort: 5432 # PostgreSQL default port
