apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - name: billing-service
        image: billing-service:latest
        ports:
        - containerPort: 4001
        - containerPort: 9001
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod