apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  selector:
    app: billing-service
  ports:
  - name: http
    protocol: TCP
    port: 4001
    targetPort: 4001
  - name: grpc
    protocol: TCP
    port: 9001
    targetPort: 9001