apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
data:
  POSTGRES_PASSWORD: "YWRtaW4=" # brother this is encoded in base64 (admin)
  JWT_SECRET: "ZzFicklFZ0hVY2tGbjAybGhTT3hRNndRV3ZFYzl5SGxuNm1tUUZiNUQ3cFJBUW5qNXhyaHl4dEt2eWp4aUR5TGJzSGlybWNQUlRFamlaclhZa0xwU210MFNhMEdZVk1ML01QYmdSUlEz" # brother this is encoded in base6

