apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: patient-service:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 4000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: BILLING_SERVICE_ADDRESS
          value: billing-service
        - name: BILLING_SERVICE_GRPC_PORT
          value: "9001"
        - name: SPRING_DATASOURCE_PASSWORD
          value:  admin
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://patient-db-service:5432/patientdb
        - name: SPRING_DATASOURCE_USERNAME
          value: admin        
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_SQL_INIT_MODE
          value: always
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
